#pragma once
#include <Windows.h>

const WORD COLOR_RED = FOREGROUND_RED;
const WORD COLOR_GREEN = FOREGROUND_GREEN;
const WORD COLOR_BLUE = FOREGROUND_BLUE;
const WORD COLOR_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN;
const WORD COLOR_MAGNETA = FOREGROUND_RED | FOREGROUND_BLUE;
const WORD COLOR_AQUA = FOREGROUND_GREEN | FOREGROUND_BLUE;
const WORD COLOR_MAGNETA_INTENSIVE = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD COLOR_YELLOW_INTENSIVE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_RED_INTENSIVE = FOREGROUND_RED | FOREGROUND_INTENSITY;
const WORD COLOR_GREEN_INTENSIVE = FOREGROUND_GREEN | FOREGROUND_INTENSITY;
const WORD COLOR_BLUE_INTENSIVE = FOREGROUND_BLUE | FOREGROUND_INTENSITY;
const WORD COLOR_WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;
const WORD COLOR_BLACK = 0;
